package com.example.flashcards.service;

import com.example.flashcards.model.Deck;
import com.example.flashcards.model.DocumentResponse;
import com.example.flashcards.model.Flashcard;
import com.example.flashcards.model.SyncResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class DeckServiceTest {

    private TestDriveStorageService fakeStorage;
    private DeckService deckService;

    static class TestDriveStorageService implements DriveStorageService {
        private Deck storedDeck = new Deck("test-deck", "Unit Test Deck", new ArrayList<>());
        private int writeCount = 0;

        @Override
        public DocumentResponse getDocument(String documentId) {
            return new DocumentResponse(documentId, "test.txt", "sample content", "text/plain");
        }

        @Override
        public Deck readDeck() {
            return storedDeck;
        }

        @Override
        public void writeDeck(Deck deck) {
            this.storedDeck = deck;
            this.writeCount++;
        }

        @Override
        public boolean isCloudConnected() {
            return false;
        }

        public int getWriteCount() {
            return writeCount;
        }
    }

    @BeforeEach
    void setUp() {
        fakeStorage = new TestDriveStorageService();
        deckService = new DeckService(fakeStorage);
    }

    @Test
    void testGetDueCards_UsesJavaStreamsToFilterCardsDueTodayOrEarlier() throws IOException {
        LocalDate today = LocalDate.now();

        Flashcard dueCard1 = new Flashcard("Q1", "A1");
        dueCard1.setId("1");
        dueCard1.setBoxNumber(1);
        dueCard1.setNextReviewDate(today);

        Flashcard overdueCard = new Flashcard("Q2", "A2");
        overdueCard.setId("2");
        overdueCard.setBoxNumber(2);
        overdueCard.setNextReviewDate(today.minusDays(3));

        Flashcard futureCard = new Flashcard("Q3", "A3");
        futureCard.setId("3");
        futureCard.setBoxNumber(3);
        futureCard.setNextReviewDate(today.plusDays(2));

        fakeStorage.readDeck().setCards(List.of(dueCard1, overdueCard, futureCard));

        List<Flashcard> dueResults = deckService.getDueCards();

        assertEquals(2, dueResults.size(), "Should only return cards due today or in the past");
        assertTrue(dueResults.stream().anyMatch(c -> "1".equals(c.getId())));
        assertTrue(dueResults.stream().anyMatch(c -> "2".equals(c.getId())));
        assertFalse(dueResults.stream().anyMatch(c -> "3".equals(c.getId())));
    }

    @Test
    void testSyncCards_ReconcilesExistingAndAppendsNewCards() throws IOException {
        Flashcard existingCard = new Flashcard("Original Q", "Original A");
        existingCard.setId("card-100");
        existingCard.setBoxNumber(1);
        fakeStorage.readDeck().setCards(new ArrayList<>(List.of(existingCard)));

        // Incoming update for existing card (progressed to Box 2)
        Flashcard updatedCard = new Flashcard("Original Q", "Original A");
        updatedCard.setId("card-100");
        updatedCard.setBoxNumber(2);
        updatedCard.setNextReviewDate(LocalDate.now().plusDays(3));

        // Brand new card generated by Python
        Flashcard newCard = new Flashcard("New Q", "New A");
        newCard.setBoxNumber(1);

        SyncResponse response = deckService.syncCards(List.of(updatedCard, newCard));

        assertEquals("SUCCESS", response.getStatus());
        assertEquals(2, response.getSyncedCount());
        assertEquals(2, response.getTotalDeckCards());

        // Verify writeDeck was invoked with reconciled POJO
        assertEquals(1, fakeStorage.getWriteCount(), "writeDeck should have been called once");
        assertEquals(2, fakeStorage.readDeck().getCards().size());
        assertEquals(2, fakeStorage.readDeck().getCards().get(0).getBoxNumber(), "Existing card should have updated box number");
    }

    @Test
    void testValidateAndSanitize_RejectsInvalidCards() {
        Flashcard blankQuestionCard = new Flashcard("", "Answer");
        assertThrows(IllegalArgumentException.class, () -> deckService.syncCards(List.of(blankQuestionCard)));

        Flashcard blankAnswerCard = new Flashcard("Question", "   ");
        assertThrows(IllegalArgumentException.class, () -> deckService.syncCards(List.of(blankAnswerCard)));
    }
}
