spring.main.web-application-type=none
spring.main.banner-mode=off
spring.ai.mcp.server.stdio=true
logging.pattern.console=
logging.file.name=target/mcp-stdio-server.log
logging.level.root=INFO
logging.level.org.springframework.ai=DEBUG
